---
apiVersion: v1
kind: Service
metadata:
  name: web-server-naz1-sv-lb
spec:
  selector:
    app: web-server-naz1
  type: LoadBalancer
  ports:
    - name: web-app
      port: 80
      targetPort: 80
      protocol: TCP
